<?php

/**
 * BaseTbLocalProva
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_certame
 * @property integer $id_prova
 * @property integer $id_responsavel
 * @property integer $id_local
 * @property boolean $status
 * @property TbCertame $TbCertame
 * @property TbLocal $TbLocal
 * @property TbProva $TbProva
 * @property TbColaborador $TbColaborador
 * @property Doctrine_Collection $TbColaboracao
 * @property Doctrine_Collection $TbLocalProva
 * 
 * @method integer             getIdCertame()      Returns the current record's "id_certame" value
 * @method integer             getIdProva()        Returns the current record's "id_prova" value
 * @method integer             getIdResponsavel()  Returns the current record's "id_responsavel" value
 * @method integer             getIdLocal()        Returns the current record's "id_local" value
 * @method boolean             getStatus()         Returns the current record's "status" value
 * @method TbCertame           getTbCertame()      Returns the current record's "TbCertame" value
 * @method TbLocal             getTbLocal()        Returns the current record's "TbLocal" value
 * @method TbProva             getTbProva()        Returns the current record's "TbProva" value
 * @method TbColaborador       getTbColaborador()  Returns the current record's "TbColaborador" value
 * @method Doctrine_Collection getTbColaboracao()  Returns the current record's "TbColaboracao" collection
 * @method Doctrine_Collection getTbLocalProva()   Returns the current record's "TbLocalProva" collection
 * @method TbLocalProva        setIdCertame()      Sets the current record's "id_certame" value
 * @method TbLocalProva        setIdProva()        Sets the current record's "id_prova" value
 * @method TbLocalProva        setIdResponsavel()  Sets the current record's "id_responsavel" value
 * @method TbLocalProva        setIdLocal()        Sets the current record's "id_local" value
 * @method TbLocalProva        setStatus()         Sets the current record's "status" value
 * @method TbLocalProva        setTbCertame()      Sets the current record's "TbCertame" value
 * @method TbLocalProva        setTbLocal()        Sets the current record's "TbLocal" value
 * @method TbLocalProva        setTbProva()        Sets the current record's "TbProva" value
 * @method TbLocalProva        setTbColaborador()  Sets the current record's "TbColaborador" value
 * @method TbLocalProva        setTbColaboracao()  Sets the current record's "TbColaboracao" collection
 * @method TbLocalProva        setTbLocalProva()   Sets the current record's "TbLocalProva" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbLocalProva extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_local_prova');
        $this->hasColumn('id_certame', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_prova', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_responsavel', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_local', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbCertame', array(
             'local' => 'id_certame',
             'foreign' => 'id'));

        $this->hasOne('TbLocal', array(
             'local' => 'id_local',
             'foreign' => 'id'));

        $this->hasOne('TbProva', array(
             'local' => 'id_prova',
             'foreign' => 'id'));

        $this->hasOne('TbColaborador', array(
             'local' => 'id_responsavel',
             'foreign' => 'id'));

        $this->hasMany('TbColaboracao', array(
             'local' => 'id',
             'foreign' => 'id_local_prova'));

        $this->hasMany('TbSalaProva as TbLocalProva', array(
             'local' => 'id',
             'foreign' => 'id_local_prova'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}