<?php

/**
 * BaseTbEscolaridade
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descricao
 * @property Doctrine_Collection $TbEscolaridade
 * 
 * @method string              getDescricao()      Returns the current record's "descricao" value
 * @method Doctrine_Collection getTbEscolaridade() Returns the current record's "TbEscolaridade" collection
 * @method TbEscolaridade      setDescricao()      Sets the current record's "descricao" value
 * @method TbEscolaridade      setTbEscolaridade() Sets the current record's "TbEscolaridade" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbEscolaridade extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_escolaridade');
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbVaga as TbEscolaridade', array(
             'local' => 'id',
             'foreign' => 'id_escolaridade'));
    }
}