<?php

/**
 * BaseTbCorrecaoRedacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descricao
 * 
 * @method string            getDescricao() Returns the current record's "descricao" value
 * @method TbCorrecaoRedacao setDescricao() Sets the current record's "descricao" value
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbCorrecaoRedacao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_correcao_redacao');
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}