<?php

/**
 * BaseTbSalaProva
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_local_prova
 * @property string $especial
 * @property string $numero_sala
 * @property integer $vagas
 * @property boolean $status
 * @property TbLocalProva $TbLocalProva
 * @property Doctrine_Collection $TbLotacaoProva
 * @property Doctrine_Collection $TbSalaProva
 * 
 * @method integer             get()               Returns the current record's "id_local_prova" value
 * @method string              get()               Returns the current record's "especial" value
 * @method string              get()               Returns the current record's "numero_sala" value
 * @method integer             get()               Returns the current record's "vagas" value
 * @method boolean             get()               Returns the current record's "status" value
 * @method TbLocalProva        get()               Returns the current record's "TbLocalProva" value
 * @method Doctrine_Collection get()               Returns the current record's "TbLotacaoProva" collection
 * @method Doctrine_Collection get()               Returns the current record's "TbSalaProva" collection
 * @method TbSalaProva         set()               Sets the current record's "id_local_prova" value
 * @method TbSalaProva         set()               Sets the current record's "especial" value
 * @method TbSalaProva         set()               Sets the current record's "numero_sala" value
 * @method TbSalaProva         set()               Sets the current record's "vagas" value
 * @method TbSalaProva         set()               Sets the current record's "status" value
 * @method TbSalaProva         set()               Sets the current record's "TbLocalProva" value
 * @method TbSalaProva         set()               Sets the current record's "TbLotacaoProva" collection
 * @method TbSalaProva         set()               Sets the current record's "TbSalaProva" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbSalaProva extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_sala_prova');
        $this->hasColumn('id_local_prova', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('especial', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('numero_sala', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('vagas', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbLocalProva', array(
             'local' => 'id_local_prova',
             'foreign' => 'id'));

        $this->hasMany('TbLotacaoProva', array(
             'local' => 'id',
             'foreign' => 'id_sala'));

        $this->hasMany('TbResponsavelSala as TbSalaProva', array(
             'local' => 'id',
             'foreign' => 'id_sala_prova'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}