<?php

/**
 * BaseTbTipoIsencao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descricao
 * @property boolean $ativo
 * @property Doctrine_Collection $TbTipoIsencao
 * 
 * @method string              get()              Returns the current record's "descricao" value
 * @method boolean             get()              Returns the current record's "ativo" value
 * @method Doctrine_Collection get()              Returns the current record's "TbTipoIsencao" collection
 * @method TbTipoIsencao       set()              Sets the current record's "descricao" value
 * @method TbTipoIsencao       set()              Sets the current record's "ativo" value
 * @method TbTipoIsencao       set()              Sets the current record's "TbTipoIsencao" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbTipoIsencao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_tipo_isencao');
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ativo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbInscricao as TbTipoIsencao', array(
             'local' => 'id',
             'foreign' => 'id_tipo_isencao'));
    }
}