<?php

/**
 * BaseTbCargo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome_cargo
 * @property string $abrev_cargo
 * @property Doctrine_Collection $TbCargo
 * 
 * @method string              getNomeCargo()   Returns the current record's "nome_cargo" value
 * @method string              getAbrevCargo()  Returns the current record's "abrev_cargo" value
 * @method Doctrine_Collection getTbCargo()     Returns the current record's "TbCargo" collection
 * @method TbCargo             setNomeCargo()   Sets the current record's "nome_cargo" value
 * @method TbCargo             setAbrevCargo()  Sets the current record's "abrev_cargo" value
 * @method TbCargo             setTbCargo()     Sets the current record's "TbCargo" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbCargo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_cargo');
        $this->hasColumn('nome_cargo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('abrev_cargo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbVaga as TbCargo', array(
             'local' => 'id',
             'foreign' => 'id_cargo'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}