<?php

/**
 * BaseTbCertame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property integer $id_tipo_certame
 * @property string $entidade_nome
 * @property string $entidade_sigla
 * @property date $data_inicio
 * @property date $data_fim
 * @property time $hora_inicio
 * @property time $hora_fim
 * @property date $data_inicio_isencao
 * @property date $data_fim_isencao
 * @property boolean $publicado
 * @property boolean $tem_redacao
 * @property boolean $tem_idioma
 * @property date $data_inicio_inscricao
 * @property date $data_fim_inscricao
 * @property TbTipoCertame $TbTipoCertame
 * @property Doctrine_Collection $TbCidadeProva
 * @property Doctrine_Collection $TbCertame
 * 
 * @method string              getNome()                  Returns the current record's "nome" value
 * @method integer             getIdTipoCertame()         Returns the current record's "id_tipo_certame" value
 * @method string              getEntidadeNome()          Returns the current record's "entidade_nome" value
 * @method string              getEntidadeSigla()         Returns the current record's "entidade_sigla" value
 * @method date                getDataInicio()            Returns the current record's "data_inicio" value
 * @method date                getDataFim()               Returns the current record's "data_fim" value
 * @method time                getHoraInicio()            Returns the current record's "hora_inicio" value
 * @method time                getHoraFim()               Returns the current record's "hora_fim" value
 * @method date                getDataInicioIsencao()     Returns the current record's "data_inicio_isencao" value
 * @method date                getDataFimIsencao()        Returns the current record's "data_fim_isencao" value
 * @method boolean             getPublicado()             Returns the current record's "publicado" value
 * @method boolean             getTemRedacao()            Returns the current record's "tem_redacao" value
 * @method boolean             getTemIdioma()             Returns the current record's "tem_idioma" value
 * @method date                getDataInicioInscricao()   Returns the current record's "data_inicio_inscricao" value
 * @method date                getDataFimInscricao()      Returns the current record's "data_fim_inscricao" value
 * @method TbTipoCertame       getTbTipoCertame()         Returns the current record's "TbTipoCertame" value
 * @method Doctrine_Collection getTbCidadeProva()         Returns the current record's "TbCidadeProva" collection
 * @method Doctrine_Collection getTbCertame()             Returns the current record's "TbCertame" collection
 * @method TbCertame           setNome()                  Sets the current record's "nome" value
 * @method TbCertame           setIdTipoCertame()         Sets the current record's "id_tipo_certame" value
 * @method TbCertame           setEntidadeNome()          Sets the current record's "entidade_nome" value
 * @method TbCertame           setEntidadeSigla()         Sets the current record's "entidade_sigla" value
 * @method TbCertame           setDataInicio()            Sets the current record's "data_inicio" value
 * @method TbCertame           setDataFim()               Sets the current record's "data_fim" value
 * @method TbCertame           setHoraInicio()            Sets the current record's "hora_inicio" value
 * @method TbCertame           setHoraFim()               Sets the current record's "hora_fim" value
 * @method TbCertame           setDataInicioIsencao()     Sets the current record's "data_inicio_isencao" value
 * @method TbCertame           setDataFimIsencao()        Sets the current record's "data_fim_isencao" value
 * @method TbCertame           setPublicado()             Sets the current record's "publicado" value
 * @method TbCertame           setTemRedacao()            Sets the current record's "tem_redacao" value
 * @method TbCertame           setTemIdioma()             Sets the current record's "tem_idioma" value
 * @method TbCertame           setDataInicioInscricao()   Sets the current record's "data_inicio_inscricao" value
 * @method TbCertame           setDataFimInscricao()      Sets the current record's "data_fim_inscricao" value
 * @method TbCertame           setTbTipoCertame()         Sets the current record's "TbTipoCertame" value
 * @method TbCertame           setTbCidadeProva()         Sets the current record's "TbCidadeProva" collection
 * @method TbCertame           setTbCertame()             Sets the current record's "TbCertame" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbCertame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_certame');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('id_tipo_certame', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('entidade_nome', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('entidade_sigla', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('data_inicio', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_fim', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('hora_inicio', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('hora_fim', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('data_inicio_isencao', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_fim_isencao', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('publicado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('tem_redacao', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('tem_idioma', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('data_inicio_inscricao', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_fim_inscricao', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbTipoCertame', array(
             'local' => 'id_tipo_certame',
             'foreign' => 'id'));

        $this->hasMany('TbCidadeProva', array(
             'local' => 'id',
             'foreign' => 'id_certame'));

        $this->hasMany('TbInscricao as TbCertame', array(
             'local' => 'id',
             'foreign' => 'id_certame'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}