<?php

/**
 * BaseTbLogradouro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property Doctrine_Collection $TbLogradouro
 * 
 * @method string              getNome()         Returns the current record's "nome" value
 * @method Doctrine_Collection getTbLogradouro() Returns the current record's "TbLogradouro" collection
 * @method TbLogradouro        setNome()         Sets the current record's "nome" value
 * @method TbLogradouro        setTbLogradouro() Sets the current record's "TbLogradouro" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbLogradouro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_logradouro');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbCandidato as TbLogradouro', array(
             'local' => 'id',
             'foreign' => 'logradouro'));
    }
}