<?php

/**
 * BaseTbFuncao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $valor
 * @property string $descricao
 * @property Doctrine_Collection $TbFuncao
 * @property Doctrine_Collection $TbColaboracao
 * 
 * @method string              get()              Returns the current record's "nome" value
 * @method string              get()              Returns the current record's "valor" value
 * @method string              get()              Returns the current record's "descricao" value
 * @method Doctrine_Collection get()              Returns the current record's "TbFuncao" collection
 * @method Doctrine_Collection get()              Returns the current record's "TbColaboracao" collection
 * @method TbFuncao            set()              Sets the current record's "nome" value
 * @method TbFuncao            set()              Sets the current record's "valor" value
 * @method TbFuncao            set()              Sets the current record's "descricao" value
 * @method TbFuncao            set()              Sets the current record's "TbFuncao" collection
 * @method TbFuncao            set()              Sets the current record's "TbColaboracao" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbFuncao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_funcao');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('valor', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbResponsavelSala as TbFuncao', array(
             'local' => 'id',
             'foreign' => 'id_funcao'));

        $this->hasMany('TbColaboracao', array(
             'local' => 'id',
             'foreign' => 'id_funcao'));
    }
}