<?php

/**
 * BaseTbLocal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property integer $id_cidade
 * @property string $sigla
 * @property string $telefone
 * @property string $endereco
 * @property integer $nsalas
 * @property boolean $status
 * @property TbCidade $TbCidade
 * @property Doctrine_Collection $TbLocal
 * 
 * @method string              get()          Returns the current record's "nome" value
 * @method integer             get()          Returns the current record's "id_cidade" value
 * @method string              get()          Returns the current record's "sigla" value
 * @method string              get()          Returns the current record's "telefone" value
 * @method string              get()          Returns the current record's "endereco" value
 * @method integer             get()          Returns the current record's "nsalas" value
 * @method boolean             get()          Returns the current record's "status" value
 * @method TbCidade            get()          Returns the current record's "TbCidade" value
 * @method Doctrine_Collection get()          Returns the current record's "TbLocal" collection
 * @method TbLocal             set()          Sets the current record's "nome" value
 * @method TbLocal             set()          Sets the current record's "id_cidade" value
 * @method TbLocal             set()          Sets the current record's "sigla" value
 * @method TbLocal             set()          Sets the current record's "telefone" value
 * @method TbLocal             set()          Sets the current record's "endereco" value
 * @method TbLocal             set()          Sets the current record's "nsalas" value
 * @method TbLocal             set()          Sets the current record's "status" value
 * @method TbLocal             set()          Sets the current record's "TbCidade" value
 * @method TbLocal             set()          Sets the current record's "TbLocal" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbLocal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_local');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('id_cidade', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sigla', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telefone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('endereco', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nsalas', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbCidade', array(
             'local' => 'id_cidade',
             'foreign' => 'id'));

        $this->hasMany('TbLocalProva as TbLocal', array(
             'local' => 'id',
             'foreign' => 'id_local'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}