<?php

/**
 * BaseTbIdioma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descricao
 * @property Doctrine_Collection $TbIdioma
 * 
 * @method string              getDescricao() Returns the current record's "descricao" value
 * @method Doctrine_Collection getTbIdioma()  Returns the current record's "TbIdioma" collection
 * @method TbIdioma            setDescricao() Sets the current record's "descricao" value
 * @method TbIdioma            setTbIdioma()  Sets the current record's "TbIdioma" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbIdioma extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_idioma');
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbInscricao as TbIdioma', array(
             'local' => 'id',
             'foreign' => 'id_idioma'));
    }
}