<?php

/**
 * BaseTbCorrecao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_prova
 * @property integer $id_inscricao
 * @property float $nota
 * @property float $nota_redacao_1
 * @property float $nota_redacao_2
 * @property float $nota_final_redacao
 * @property text $obs
 * @property integer $id_eliminacao_redacao
 * @property TbProva $TbProva
 * @property TbInscricao $TbInscricao
 * 
 * @method integer     getIdProva()               Returns the current record's "id_prova" value
 * @method integer     getIdInscricao()           Returns the current record's "id_inscricao" value
 * @method float       getNota()                  Returns the current record's "nota" value
 * @method float       getNotaRedacao1()          Returns the current record's "nota_redacao_1" value
 * @method float       getNotaRedacao2()          Returns the current record's "nota_redacao_2" value
 * @method float       getNotaFinalRedacao()      Returns the current record's "nota_final_redacao" value
 * @method text        getObs()                   Returns the current record's "obs" value
 * @method integer     getIdEliminacaoRedacao()   Returns the current record's "id_eliminacao_redacao" value
 * @method TbProva     getTbProva()               Returns the current record's "TbProva" value
 * @method TbInscricao getTbInscricao()           Returns the current record's "TbInscricao" value
 * @method TbCorrecao  setIdProva()               Sets the current record's "id_prova" value
 * @method TbCorrecao  setIdInscricao()           Sets the current record's "id_inscricao" value
 * @method TbCorrecao  setNota()                  Sets the current record's "nota" value
 * @method TbCorrecao  setNotaRedacao1()          Sets the current record's "nota_redacao_1" value
 * @method TbCorrecao  setNotaRedacao2()          Sets the current record's "nota_redacao_2" value
 * @method TbCorrecao  setNotaFinalRedacao()      Sets the current record's "nota_final_redacao" value
 * @method TbCorrecao  setObs()                   Sets the current record's "obs" value
 * @method TbCorrecao  setIdEliminacaoRedacao()   Sets the current record's "id_eliminacao_redacao" value
 * @method TbCorrecao  setTbProva()               Sets the current record's "TbProva" value
 * @method TbCorrecao  setTbInscricao()           Sets the current record's "TbInscricao" value
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbCorrecao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_correcao');
        $this->hasColumn('id_prova', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_inscricao', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nota', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('nota_redacao_1', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('nota_redacao_2', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('nota_final_redacao', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('obs', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('id_eliminacao_redacao', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbProva', array(
             'local' => 'id_prova',
             'foreign' => 'id'));

        $this->hasOne('TbInscricao', array(
             'local' => 'id_inscricao',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}