<?php

/**
 * BaseTbCidade
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $estado
 * @property string $nome
 * @property TbEstado $TbEstado
 * @property Doctrine_Collection $TbCandidato
 * @property Doctrine_Collection $TbCidadeProva
 * @property Doctrine_Collection $TbLocal
 * @property Doctrine_Collection $TbCidade
 * @property Doctrine_Collection $TbColaborador
 * 
 * @method integer             getEstado()        Returns the current record's "estado" value
 * @method string              getNome()          Returns the current record's "nome" value
 * @method TbEstado            getTbEstado()      Returns the current record's "TbEstado" value
 * @method Doctrine_Collection getTbCandidato()   Returns the current record's "TbCandidato" collection
 * @method Doctrine_Collection getTbCidadeProva() Returns the current record's "TbCidadeProva" collection
 * @method Doctrine_Collection getTbLocal()       Returns the current record's "TbLocal" collection
 * @method Doctrine_Collection getTbCidade()      Returns the current record's "TbCidade" collection
 * @method Doctrine_Collection getTbColaborador() Returns the current record's "TbColaborador" collection
 * @method TbCidade            setEstado()        Sets the current record's "estado" value
 * @method TbCidade            setNome()          Sets the current record's "nome" value
 * @method TbCidade            setTbEstado()      Sets the current record's "TbEstado" value
 * @method TbCidade            setTbCandidato()   Sets the current record's "TbCandidato" collection
 * @method TbCidade            setTbCidadeProva() Sets the current record's "TbCidadeProva" collection
 * @method TbCidade            setTbLocal()       Sets the current record's "TbLocal" collection
 * @method TbCidade            setTbCidade()      Sets the current record's "TbCidade" collection
 * @method TbCidade            setTbColaborador() Sets the current record's "TbColaborador" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbCidade extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_cidade');
        $this->hasColumn('estado', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbEstado', array(
             'local' => 'estado',
             'foreign' => 'id'));

        $this->hasMany('TbCandidato', array(
             'local' => 'id',
             'foreign' => 'id_cidade'));

        $this->hasMany('TbCidadeProva', array(
             'local' => 'id',
             'foreign' => 'id_cidade'));

        $this->hasMany('TbLocal', array(
             'local' => 'id',
             'foreign' => 'id_cidade'));

        $this->hasMany('TbVaga as TbCidade', array(
             'local' => 'id',
             'foreign' => 'id_cidade'));

        $this->hasMany('TbColaborador', array(
             'local' => 'id',
             'foreign' => 'id_cidade'));
    }
}