<?php

/**
 * BaseTbQuestoes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_prova
 * @property integer $numero
 * @property float $peso
 * @property char $gabarito
 * @property TbProva $TbProva
 * 
 * @method integer    getIdProva()  Returns the current record's "id_prova" value
 * @method integer    getNumero()   Returns the current record's "numero" value
 * @method float      getPeso()     Returns the current record's "peso" value
 * @method char       getGabarito() Returns the current record's "gabarito" value
 * @method TbProva    getTbProva()  Returns the current record's "TbProva" value
 * @method TbQuestoes setIdProva()  Sets the current record's "id_prova" value
 * @method TbQuestoes setNumero()   Sets the current record's "numero" value
 * @method TbQuestoes setPeso()     Sets the current record's "peso" value
 * @method TbQuestoes setGabarito() Sets the current record's "gabarito" value
 * @method TbQuestoes setTbProva()  Sets the current record's "TbProva" value
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbQuestoes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_questoes');
        $this->hasColumn('id_prova', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('peso', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('gabarito', 'char', null, array(
             'type' => 'char',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbProva', array(
             'local' => 'id_prova',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}