<?php

/**
 * BaseTbLotacaoProva
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_sala
 * @property integer $id_inscricao
 * @property TbSalaProva $TbSalaProva
 * @property TbInscricao $TbInscricao
 * 
 * @method integer        get()             Returns the current record's "id_sala" value
 * @method integer        get()             Returns the current record's "id_inscricao" value
 * @method TbSalaProva    get()             Returns the current record's "TbSalaProva" value
 * @method TbInscricao    get()             Returns the current record's "TbInscricao" value
 * @method TbLotacaoProva set()             Sets the current record's "id_sala" value
 * @method TbLotacaoProva set()             Sets the current record's "id_inscricao" value
 * @method TbLotacaoProva set()             Sets the current record's "TbSalaProva" value
 * @method TbLotacaoProva set()             Sets the current record's "TbInscricao" value
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbLotacaoProva extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_lotacao_prova');
        $this->hasColumn('id_sala', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_inscricao', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbSalaProva', array(
             'local' => 'id_sala',
             'foreign' => 'id'));

        $this->hasOne('TbInscricao', array(
             'local' => 'id_inscricao',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}