<?php

/**
 * BaseTbRgtipo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $rgtipo
 * @property Doctrine_Collection $TbRgtipo
 * @property Doctrine_Collection $TbColaborador
 * 
 * @method string              getRgtipo()        Returns the current record's "rgtipo" value
 * @method Doctrine_Collection getTbRgtipo()      Returns the current record's "TbRgtipo" collection
 * @method Doctrine_Collection getTbColaborador() Returns the current record's "TbColaborador" collection
 * @method TbRgtipo            setRgtipo()        Sets the current record's "rgtipo" value
 * @method TbRgtipo            setTbRgtipo()      Sets the current record's "TbRgtipo" collection
 * @method TbRgtipo            setTbColaborador() Sets the current record's "TbColaborador" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbRgtipo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_rgtipo');
        $this->hasColumn('rgtipo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbCandidato as TbRgtipo', array(
             'local' => 'id',
             'foreign' => 'rgtipo'));

        $this->hasMany('TbColaborador', array(
             'local' => 'id',
             'foreign' => 'rgtipo'));
    }
}