<?php

/**
 * BaseTbCandidato
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property string $sexo
 * @property string $rg
 * @property integer $rgtipo
 * @property integer $rguf
 * @property integer $rgemissor
 * @property string $cpf
 * @property string $pai
 * @property string $mae
 * @property date $data_nascimento
 * @property integer $estado_nascimento
 * @property string $cidade_nascimento
 * @property string $cep
 * @property string $endereco
 * @property string $numero
 * @property string $complemento
 * @property string $bairro
 * @property string $id_cidade
 * @property integer $id_estado
 * @property string $tel1
 * @property string $tel2
 * @property string $tel3
 * @property string $email
 * @property integer $user_id
 * @property TbEstado $TbEstado
 * @property TbRgtipo $TbRgtipo
 * @property TbRgemissor $TbRgemissor
 * @property Doctrine_Collection $TbInscricao
 * 
 * @method string              get()                  Returns the current record's "nome" value
 * @method string              get()                  Returns the current record's "sexo" value
 * @method string              get()                  Returns the current record's "rg" value
 * @method integer             get()                  Returns the current record's "rgtipo" value
 * @method integer             get()                  Returns the current record's "rguf" value
 * @method integer             get()                  Returns the current record's "rgemissor" value
 * @method string              get()                  Returns the current record's "cpf" value
 * @method string              get()                  Returns the current record's "pai" value
 * @method string              get()                  Returns the current record's "mae" value
 * @method date                get()                  Returns the current record's "data_nascimento" value
 * @method integer             get()                  Returns the current record's "estado_nascimento" value
 * @method string              get()                  Returns the current record's "cidade_nascimento" value
 * @method string              get()                  Returns the current record's "cep" value
 * @method string              get()                  Returns the current record's "endereco" value
 * @method string              get()                  Returns the current record's "numero" value
 * @method string              get()                  Returns the current record's "complemento" value
 * @method string              get()                  Returns the current record's "bairro" value
 * @method string              get()                  Returns the current record's "id_cidade" value
 * @method integer             get()                  Returns the current record's "id_estado" value
 * @method string              get()                  Returns the current record's "tel1" value
 * @method string              get()                  Returns the current record's "tel2" value
 * @method string              get()                  Returns the current record's "tel3" value
 * @method string              get()                  Returns the current record's "email" value
 * @method integer             get()                  Returns the current record's "user_id" value
 * @method TbEstado            get()                  Returns the current record's "TbEstado" value
 * @method TbRgtipo            get()                  Returns the current record's "TbRgtipo" value
 * @method TbRgemissor         get()                  Returns the current record's "TbRgemissor" value
 * @method Doctrine_Collection get()                  Returns the current record's "TbInscricao" collection
 * @method TbCandidato         set()                  Sets the current record's "nome" value
 * @method TbCandidato         set()                  Sets the current record's "sexo" value
 * @method TbCandidato         set()                  Sets the current record's "rg" value
 * @method TbCandidato         set()                  Sets the current record's "rgtipo" value
 * @method TbCandidato         set()                  Sets the current record's "rguf" value
 * @method TbCandidato         set()                  Sets the current record's "rgemissor" value
 * @method TbCandidato         set()                  Sets the current record's "cpf" value
 * @method TbCandidato         set()                  Sets the current record's "pai" value
 * @method TbCandidato         set()                  Sets the current record's "mae" value
 * @method TbCandidato         set()                  Sets the current record's "data_nascimento" value
 * @method TbCandidato         set()                  Sets the current record's "estado_nascimento" value
 * @method TbCandidato         set()                  Sets the current record's "cidade_nascimento" value
 * @method TbCandidato         set()                  Sets the current record's "cep" value
 * @method TbCandidato         set()                  Sets the current record's "endereco" value
 * @method TbCandidato         set()                  Sets the current record's "numero" value
 * @method TbCandidato         set()                  Sets the current record's "complemento" value
 * @method TbCandidato         set()                  Sets the current record's "bairro" value
 * @method TbCandidato         set()                  Sets the current record's "id_cidade" value
 * @method TbCandidato         set()                  Sets the current record's "id_estado" value
 * @method TbCandidato         set()                  Sets the current record's "tel1" value
 * @method TbCandidato         set()                  Sets the current record's "tel2" value
 * @method TbCandidato         set()                  Sets the current record's "tel3" value
 * @method TbCandidato         set()                  Sets the current record's "email" value
 * @method TbCandidato         set()                  Sets the current record's "user_id" value
 * @method TbCandidato         set()                  Sets the current record's "TbEstado" value
 * @method TbCandidato         set()                  Sets the current record's "TbRgtipo" value
 * @method TbCandidato         set()                  Sets the current record's "TbRgemissor" value
 * @method TbCandidato         set()                  Sets the current record's "TbInscricao" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbCandidato extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_candidato');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sexo', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('rg', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('rgtipo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rguf', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rgemissor', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cpf', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('pai', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mae', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('data_nascimento', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('estado_nascimento', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cidade_nascimento', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cep', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('endereco', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('numero', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('complemento', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('bairro', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('id_cidade', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('id_estado', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tel1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tel2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tel3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbEstado', array(
             'local' => 'estado_nascimento',
             'foreign' => 'id'));

        $this->hasOne('TbRgtipo', array(
             'local' => 'rgtipo',
             'foreign' => 'id'));

        $this->hasOne('TbRgemissor', array(
             'local' => 'rgemissor',
             'foreign' => 'id'));

        $this->hasMany('TbInscricao', array(
             'local' => 'id',
             'foreign' => 'id_candidato'));
    }
}