<?php

/**
 * BaseTbInscricao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_candidato
 * @property integer $id_certame
 * @property integer $id_vaga
 * @property integer $id_condicao_especial
 * @property integer $id_cidade_prova
 * @property integer $boleto
 * @property integer $pago
 * @property integer $vaga_deficiente
 * @property integer $id_idioma
 * @property TbCandidato $TbCandidato
 * @property TbCertame $TbCertame
 * @property TbIdioma $TbIdioma
 * @property TbVaga $TbVaga
 * @property TbCondicaoEspecial $TbCondicaoEspecial
 * @property TbCidadeProva $TbCidadeProva
 * @property Doctrine_Collection $TbInscricao
 * @property Doctrine_Collection $TbLotacaoProva
 * 
 * @method integer             getIdCandidato()          Returns the current record's "id_candidato" value
 * @method integer             getIdCertame()            Returns the current record's "id_certame" value
 * @method integer             getIdVaga()               Returns the current record's "id_vaga" value
 * @method integer             getIdCondicaoEspecial()   Returns the current record's "id_condicao_especial" value
 * @method integer             getIdCidadeProva()        Returns the current record's "id_cidade_prova" value
 * @method integer             getBoleto()               Returns the current record's "boleto" value
 * @method integer             getPago()                 Returns the current record's "pago" value
 * @method integer             getVagaDeficiente()       Returns the current record's "vaga_deficiente" value
 * @method integer             getIdIdioma()             Returns the current record's "id_idioma" value
 * @method TbCandidato         getTbCandidato()          Returns the current record's "TbCandidato" value
 * @method TbCertame           getTbCertame()            Returns the current record's "TbCertame" value
 * @method TbIdioma            getTbIdioma()             Returns the current record's "TbIdioma" value
 * @method TbVaga              getTbVaga()               Returns the current record's "TbVaga" value
 * @method TbCondicaoEspecial  getTbCondicaoEspecial()   Returns the current record's "TbCondicaoEspecial" value
 * @method TbCidadeProva       getTbCidadeProva()        Returns the current record's "TbCidadeProva" value
 * @method Doctrine_Collection getTbInscricao()          Returns the current record's "TbInscricao" collection
 * @method Doctrine_Collection getTbLotacaoProva()       Returns the current record's "TbLotacaoProva" collection
 * @method TbInscricao         setIdCandidato()          Sets the current record's "id_candidato" value
 * @method TbInscricao         setIdCertame()            Sets the current record's "id_certame" value
 * @method TbInscricao         setIdVaga()               Sets the current record's "id_vaga" value
 * @method TbInscricao         setIdCondicaoEspecial()   Sets the current record's "id_condicao_especial" value
 * @method TbInscricao         setIdCidadeProva()        Sets the current record's "id_cidade_prova" value
 * @method TbInscricao         setBoleto()               Sets the current record's "boleto" value
 * @method TbInscricao         setPago()                 Sets the current record's "pago" value
 * @method TbInscricao         setVagaDeficiente()       Sets the current record's "vaga_deficiente" value
 * @method TbInscricao         setIdIdioma()             Sets the current record's "id_idioma" value
 * @method TbInscricao         setTbCandidato()          Sets the current record's "TbCandidato" value
 * @method TbInscricao         setTbCertame()            Sets the current record's "TbCertame" value
 * @method TbInscricao         setTbIdioma()             Sets the current record's "TbIdioma" value
 * @method TbInscricao         setTbVaga()               Sets the current record's "TbVaga" value
 * @method TbInscricao         setTbCondicaoEspecial()   Sets the current record's "TbCondicaoEspecial" value
 * @method TbInscricao         setTbCidadeProva()        Sets the current record's "TbCidadeProva" value
 * @method TbInscricao         setTbInscricao()          Sets the current record's "TbInscricao" collection
 * @method TbInscricao         setTbLotacaoProva()       Sets the current record's "TbLotacaoProva" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbInscricao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_inscricao');
        $this->hasColumn('id_candidato', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_certame', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_vaga', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_condicao_especial', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_cidade_prova', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('boleto', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pago', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('vaga_deficiente', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_idioma', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbCandidato', array(
             'local' => 'id_candidato',
             'foreign' => 'id'));

        $this->hasOne('TbCertame', array(
             'local' => 'id_certame',
             'foreign' => 'id'));

        $this->hasOne('TbIdioma', array(
             'local' => 'id_idioma',
             'foreign' => 'id'));

        $this->hasOne('TbVaga', array(
             'local' => 'id_vaga',
             'foreign' => 'id'));

        $this->hasOne('TbCondicaoEspecial', array(
             'local' => 'id_condicao_especial',
             'foreign' => 'id'));

        $this->hasOne('TbCidadeProva', array(
             'local' => 'id_cidade_prova',
             'foreign' => 'id'));

        $this->hasMany('TbCorrecao as TbInscricao', array(
             'local' => 'id',
             'foreign' => 'id_inscricao'));

        $this->hasMany('TbLotacaoProva', array(
             'local' => 'id',
             'foreign' => 'id_inscricao'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}