<?php

/**
 * BaseTbTipoCertame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descricao
 * @property Doctrine_Collection $TbTipoCertame
 * 
 * @method string              getDescricao()     Returns the current record's "descricao" value
 * @method Doctrine_Collection getTbTipoCertame() Returns the current record's "TbTipoCertame" collection
 * @method TbTipoCertame       setDescricao()     Sets the current record's "descricao" value
 * @method TbTipoCertame       setTbTipoCertame() Sets the current record's "TbTipoCertame" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbTipoCertame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_tipo_certame');
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbCertame as TbTipoCertame', array(
             'local' => 'id',
             'foreign' => 'id_tipo_certame'));
    }
}