<?php

/**
 * BaseTbCidadeProva
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_certame
 * @property integer $id_cidade
 * @property TbCidade $TbCidade
 * @property TbCertame $TbCertame
 * @property Doctrine_Collection $TbCidadeProva
 * 
 * @method integer             get()              Returns the current record's "id_certame" value
 * @method integer             get()              Returns the current record's "id_cidade" value
 * @method TbCidade            get()              Returns the current record's "TbCidade" value
 * @method TbCertame           get()              Returns the current record's "TbCertame" value
 * @method Doctrine_Collection get()              Returns the current record's "TbCidadeProva" collection
 * @method TbCidadeProva       set()              Sets the current record's "id_certame" value
 * @method TbCidadeProva       set()              Sets the current record's "id_cidade" value
 * @method TbCidadeProva       set()              Sets the current record's "TbCidade" value
 * @method TbCidadeProva       set()              Sets the current record's "TbCertame" value
 * @method TbCidadeProva       set()              Sets the current record's "TbCidadeProva" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbCidadeProva extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_cidade_prova');
        $this->hasColumn('id_certame', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_cidade', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbCidade', array(
             'local' => 'id_cidade',
             'foreign' => 'id'));

        $this->hasOne('TbCertame', array(
             'local' => 'id_certame',
             'foreign' => 'id'));

        $this->hasMany('TbInscricao as TbCidadeProva', array(
             'local' => 'id',
             'foreign' => 'id_cidade_prova'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}