<?php

/**
 * BaseTbResponsavelSala
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_colaborador
 * @property integer $id_sala_prova
 * @property integer $id_funcao
 * @property TbSalaProva $TbSalaProva
 * @property TbFuncao $TbFuncao
 * @property TbColaborador $TbColaborador
 * 
 * @method integer           get()               Returns the current record's "id_colaborador" value
 * @method integer           get()               Returns the current record's "id_sala_prova" value
 * @method integer           get()               Returns the current record's "id_funcao" value
 * @method TbSalaProva       get()               Returns the current record's "TbSalaProva" value
 * @method TbFuncao          get()               Returns the current record's "TbFuncao" value
 * @method TbColaborador     get()               Returns the current record's "TbColaborador" value
 * @method TbResponsavelSala set()               Sets the current record's "id_colaborador" value
 * @method TbResponsavelSala set()               Sets the current record's "id_sala_prova" value
 * @method TbResponsavelSala set()               Sets the current record's "id_funcao" value
 * @method TbResponsavelSala set()               Sets the current record's "TbSalaProva" value
 * @method TbResponsavelSala set()               Sets the current record's "TbFuncao" value
 * @method TbResponsavelSala set()               Sets the current record's "TbColaborador" value
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbResponsavelSala extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_responsavel_sala');
        $this->hasColumn('id_colaborador', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_sala_prova', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_funcao', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbSalaProva', array(
             'local' => 'id_sala_prova',
             'foreign' => 'id'));

        $this->hasOne('TbFuncao', array(
             'local' => 'id_funcao',
             'foreign' => 'id'));

        $this->hasOne('TbColaborador', array(
             'local' => 'id_colaborador',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}