<?php

/**
 * BaseTbProva
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_certame
 * @property integer $id_vaga
 * @property integer $id_cidade_prova
 * @property date $data_inicio
 * @property time $hora_inicio
 * @property string $duracao
 * @property TbCertame $TbCertame
 * @property TbVaga $TbVaga
 * @property TbProva $TbProva
 * @property TbCidadeProva $TbCidadeProva
 * @property Doctrine_Collection $TbLocalProva
 * 
 * @method integer             get()                Returns the current record's "id_certame" value
 * @method integer             get()                Returns the current record's "id_vaga" value
 * @method integer             get()                Returns the current record's "id_cidade_prova" value
 * @method date                get()                Returns the current record's "data_inicio" value
 * @method time                get()                Returns the current record's "hora_inicio" value
 * @method string              get()                Returns the current record's "duracao" value
 * @method TbCertame           get()                Returns the current record's "TbCertame" value
 * @method TbVaga              get()                Returns the current record's "TbVaga" value
 * @method TbProva             get()                Returns the current record's "TbProva" value
 * @method TbCidadeProva       get()                Returns the current record's "TbCidadeProva" value
 * @method Doctrine_Collection get()                Returns the current record's "TbLocalProva" collection
 * @method TbProva             set()                Sets the current record's "id_certame" value
 * @method TbProva             set()                Sets the current record's "id_vaga" value
 * @method TbProva             set()                Sets the current record's "id_cidade_prova" value
 * @method TbProva             set()                Sets the current record's "data_inicio" value
 * @method TbProva             set()                Sets the current record's "hora_inicio" value
 * @method TbProva             set()                Sets the current record's "duracao" value
 * @method TbProva             set()                Sets the current record's "TbCertame" value
 * @method TbProva             set()                Sets the current record's "TbVaga" value
 * @method TbProva             set()                Sets the current record's "TbProva" value
 * @method TbProva             set()                Sets the current record's "TbCidadeProva" value
 * @method TbProva             set()                Sets the current record's "TbLocalProva" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbProva extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_prova');
        $this->hasColumn('id_certame', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_vaga', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_cidade_prova', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('data_inicio', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hora_inicio', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('duracao', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));


        $this->index('id_prova', array(
             'fields' => 
             array(
              0 => 'id_prova',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbCertame', array(
             'local' => 'id_certame',
             'foreign' => 'id'));

        $this->hasOne('TbVaga', array(
             'local' => 'id_vaga',
             'foreign' => 'id'));

        $this->hasOne('TbProva', array(
             'local' => 'id_prova',
             'foreign' => 'id'));

        $this->hasOne('TbCidadeProva', array(
             'local' => 'id_cidade_prova',
             'foreign' => 'id'));

        $this->hasMany('TbLocalProva', array(
             'local' => 'id',
             'foreign' => 'id_prova'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}