<?php

/**
 * BaseTbFuncao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property float $valor
 * @property string $descricao
 * @property Doctrine_Collection $TbFuncao
 * 
 * @method string              getNome()      Returns the current record's "nome" value
 * @method float               getValor()     Returns the current record's "valor" value
 * @method string              getDescricao() Returns the current record's "descricao" value
 * @method Doctrine_Collection getTbFuncao()  Returns the current record's "TbFuncao" collection
 * @method TbFuncao            setNome()      Sets the current record's "nome" value
 * @method TbFuncao            setValor()     Sets the current record's "valor" value
 * @method TbFuncao            setDescricao() Sets the current record's "descricao" value
 * @method TbFuncao            setTbFuncao()  Sets the current record's "TbFuncao" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbFuncao extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_funcao');
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('valor', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbResponsavelSala as TbFuncao', array(
             'local' => 'id',
             'foreign' => 'id_funcao'));
    }
}