generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbFuncao
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_funcao
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
      filter:  
          display: [nome,descricao]
      form:    ~
      edit:    ~
      new:     ~
