<?php

/**
 * SfMessages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SfMessages extends BaseSfMessages
{
public function getEnviromentName(){
    switch ($this->getEnviroment()){
        case 0:            
            return 'Admin';
        case 1:            
            return 'Professor';
        case 2:            
            return 'Student';
            
    }
}
    
}
