<?php

/**
 * TbCandidatoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbCandidatoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbCandidatoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbCandidato');
    }
}