<?php

/**
 * TbCargoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbCargoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbCargoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbCargo');
    }
}