<?php

/**
 * TbCertameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbCertameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbCertameTable
     */
   


   public static function getInstance()
    {
        return Doctrine_Core::getTable('TbCertame');
    }
    
       public static function getCertameAtivos(){
        $q = Doctrine_Query::create()->from('TbCertame')->where('publicado = 1');
           return $q;
           
           
       }
    
    
}