<?php

/**
 * TbCidadeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbCidadeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbCidadeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbCidade');
    }
    
    public static function retrieveForSelect($q, $limit = 10) {
        $q = Doctrine_Query::create()
            ->from('TbCidade')
            ->where('nome like ?', '%' . $q . '%')
//            ->addOrderBy('nome')
            ->limit($limit);

        $disciplines = array();

        foreach ($q->execute() as $discipline) {
            $disciplines[$discipline->getId()] =  $discipline->getNome().' /'.$discipline->getTbEstado()->getUf();
        }
        return $disciplines;
    }
    
}