<?php

/**
 * TbCidadeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbCidadeTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object TbCidadeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('TbCidade');
    }

    public static function retrieveForSelect($q, $limit = 30) {
//        $limit = 30;

        if (strpos($q, '-') != false) {

            $nomes = explode('-', strtolower($q));
//            var_dump($nomes);
            $query = Doctrine_Query::create()
                    ->from('TbCidade c ')
                    ->where('c.nome like ?', '%' . $nomes[0] . '%')
                    ->innerJoin('c.TbEstado e')
                    ->andWhere('e.UF like ? ','%' . $nomes[1] . '%')
//            ->addOrderBy('id_estado')
                    ->limit($limit);
        } else {
            $query = Doctrine_Query::create()
                    ->from('TbCidade')
                    ->where('nome like ?', '%' . $q . '%')
//            ->addOrderBy('id_estado')
                    ->limit($limit);
        }
//    $cidades = TbCidadeTable::getInstance()->findBy('nome',$q);

        $disciplines = array();
        $cidades = $query->execute();
        foreach ($cidades as $discipline) {
            $disciplines[$discipline->getId()] = $discipline->getNome() . ' -' . $discipline->getTbEstado()->getUf();
        }
        return $disciplines;
    }

}
