<?php

/**
 * TbCidadeProvaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbCidadeProvaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbCidadeProvaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbCidadeProva');
    }
}