<?php

/**
 * TbCondicaoEspecialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbCondicaoEspecialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbCondicaoEspecialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbCondicaoEspecial');
    }
}