<?php

/**
 * TbCorrecaoRedacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbCorrecaoRedacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbCorrecaoRedacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbCorrecaoRedacao');
    }
}