<?php

/**
 * TbCorrecaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbCorrecaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbCorrecaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbCorrecao');
    }
     public function getPorProva() {
          $q = Doctrine_Query::create()->from('TbCorrecao')->where('id_prova = ?',  sfContext::getInstance()->getUser()->getAttribute('prova'));
          return $q;
           
    }
    
}