<?php

/**
 * TbColaboracaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbColaboracaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbColaboracaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbColaboracao');
    }
    
     public function getPorCertame() {
          $q = Doctrine_Query::create()->from('TbColaboracao')->where('id_certame = ?',  sfContext::getInstance()->getUser()->getAttribute('certame'));
          return $q;
           
    }
    
}