<?php

/**
 * TbColaboradorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbColaboradorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbColaboradorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbColaborador');
    }
}