<?php

/**
 * TbCorrecaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbCorrecaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbCorrecaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbCorrecao');
    }
}