<?php

/**
 * TbEliminacaoRedacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbEliminacaoRedacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbEliminacaoRedacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbEliminacaoRedacao');
    }
}