<?php

/**
 * TbEstadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbEstadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbEstadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbEstado');
    }
}