<?php

/**
 * TbFuncaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbFuncaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbFuncaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbFuncao');
    }
}