<?php

/**
 * TbIdiomaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbIdiomaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbIdiomaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbIdioma');
    }
}