<?php

/**
 * TbInscricaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbInscricaoTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object TbInscricaoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('TbInscricao');
    }

    public static function getInscricaoCandidato() {
        $q = Doctrine_Query::create()->from('TbInscricao ins')
                        ->innerJoin('ins.TbCandidato cand')->
                        where('cand.user_id = ?', sfContext::getInstance()->getUser()->getId())->andWhere('id_certame = ?', sfContext::getInstance()->getUser()->getAttribute('certame')->getId());
        return $q;
    }

    public function getPorCertame() {
        $q = Doctrine_Query::create()->from('TbInscricao')->where('id_certame = ?', sfContext::getInstance()->getUser()->getAttribute('certame'));
        return $q;
    }

    public static function generateReport(sfWebRequest $request) {
        $query = Doctrine_Query::create()->from('TbInscricao ins')
                ->innerJoin('ins.TbCandidato cand')
                ->innerJoin('ins.TbCidadeProva cidade')
                ->innerJoin('ins.TbVaga vag');
        $form = new RelatorioInscricaoForm();
        foreach ($form->getFields() as $field) {
            if ($request->hasParameter($field)) {
                if (in_array($field, array('pago','deficiente','isencao', 'isento'))){
                 $query->andWhere($field.' = '.($request->getParameter($field) == 'on' ? true: false ));                    
                }
                if ($field == 'id_cidade'){
                 $query->andWhere('cidade.id = '.$request->getParameter($field));                       
                }
                if ($field == 'id_vaga'){
                 $query->andWhere('vag.id = '.$request->getParameter($field));                          
                }
            }
        }
        $query->orderBy('cand.nome ASC');
        return $query;
    }

}
