<?php

/**
 * TbLocalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbLocalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbLocalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbLocal');
    }
}