<?php

/**
 * TbLogradouroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbLogradouroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbLogradouroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbLogradouro');
    }
}