<?php

/**
 * TbLocalProvaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbLocalProvaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbLocalProvaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbLocalProva');
    }
    
     public function getPorCertame() {
          $q = Doctrine_Query::create()->from('TbLocalProva')->where('id_certame = ?',  sfContext::getInstance()->getUser()->getAttribute('certame'));
          return $q;
           
    }
}