<?php

/**
 * TbProvaVagaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbProvaVagaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbProvaVagaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbProvaVaga');
    }
    
    public function getPorProva() {
          $q = Doctrine_Query::create()->from('TbProvaVaga')->where('id_prova = ?',  sfContext::getInstance()->getUser()->getAttribute('prova'));
          return $q;
           
    }
}