<?php

/**
 * TbProvaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbProvaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbProvaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbProva');
    }
}