<?php

/**
 * TbProvaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbProvaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbProvaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbProva');
    }
    
     public function getPorCertame() {
          $q = Doctrine_Query::create()->from('TbProva')->where('id_certame = ?',  sfContext::getInstance()->getUser()->getAttribute('certame'));
          return $q;
           
    }
}