<?php

/**
 * TbResponsavelSalaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbResponsavelSalaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbResponsavelSalaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbResponsavelSala');
    }
}