<?php

/**
 * TbRgtipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbRgtipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbRgtipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbRgtipo');
    }
}