<?php

/**
 * TbTipoCertameTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbTipoCertameTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbTipoCertameTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbTipoCertame');
    }
}