<?php

/**
 * TbTipoIsencaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbTipoIsencaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbTipoIsencaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbTipoIsencao');
    }
    
    public function getPorAtivo() {
        
          $q = Doctrine_Query::create()->from('TbTipoIsencao')->where('ativo = 1');
          return $q;
           
    }
}