<?php

/**
 * TbVagaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TbVagaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TbVagaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TbVaga');
    }
}