generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbInscricao
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          tb_inscricao
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
          relatorio:
              label: Relatório Inscritos
          outros:
              label: Dados Estatisticos Inscritos
      fields:  
          id_vaga:
              label: Vaga
          TbVaga:
              label: Vaga
          id_cidade_prova:
              label: Cidade de Prova
          TbCidadeProva:
              label: Cidade de Prova
      list:
          title: Lista de Inscrições no Certame 
          display: [boleto,TbVaga,TbCidadeProva,pago,vaga_deficiente,isencao,isento] 
          actions: 
              relatorio: ~
              outros: ~
          batch_actions: []
          table_method:  getPorCertame
          object_actions:
              _show: ~
              boleto: 
                  label: Gerar Boleto
      filter:  
          display: [id_vaga,id_cidade_prova,pago,vaga_deficiente,isencao,isento]
      form:    ~
      edit:    ~
      new:     ~
