generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbInscricao
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          tb_inscricao
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:           
      fields:  ~
      list:
          title: Lista de Inscrições no Certame 
          display: [boleto,TbVaga,TbCidadeProva,pago,vaga_deficiente] 
          actions: []
          batch_actions: []
          object_actions:
              _show: ~
              boleto: 
                  label: Gerar Boleto
      filter:  
          display: [id_vaga,id_cidade_prova,pago,vaga_deficiente]
      form:    ~
      edit:    ~
      new:     ~
