generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbSalaProva
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_sala_prova
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
              presenca: 
                  label: Lista de Chamada
              presenca_porta: 
                  label: Listagem  de Porta
              prova_discursiva: 
                  label: Listagem  de Conferência Prova Discursiva
              LocalProva: 
                  label: Lista de Locais de Prova
      fields:  ~
      list:
          actions:
              _new: ~   
              presenca: ~
              presenca_porta: ~
              prova_discursiva: ~
              LocalProva: 
                  label: Lista de Locais de Prova
          batch_actions:
              delete: ~               
          title: Lista de Salas de Prova
          display: [numero_sala,especial,vagas,status]
          table_method:  getPorLocalProva
          object_actions:
              edit: ~
              delete: ~
      filter:  
          class: false
      form:    ~
      edit:    ~
      new:     ~
