generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbQuestoes
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          tb_questoes
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
          actions:
              _new: ~
              Gabarito: ~
              Provas:
                  label: Lista de Provas
          title: Lista de Quest천es da Prova
          table_method:  getPorProva
          display: [numero,peso]
      filter:            
          class: false
      form:    ~
      edit:    
          title: Editando Quest찾o da Prova
      new:     
          title: Nova Quest찾o da Prova
      show:
          title: Exibindo Quest찾o
          display: [numero,peso,gabarito,discursiva]
