<?php

/**
 * sfGuardModuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardModuleTable extends PluginsfGuardModuleTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardModuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardModule');
    }
}