generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbInscricao
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_inscricao
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
          title: Lista de Inscrições
          display: [TbCertame,TbVaga]
          table_method:  getInscricaoCandidato
      filter:  
          class: false
      form:    ~
      edit:    ~
      new:     ~
