generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbInscricao
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          tb_inscricao
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
          _show: 
              label: "Comprovante de Inscrição"
      fields:  
          TbVaga: 
              label: Vaga
          TbCidadeProva:
              label: Cidade de Prova
      list:
          title: Lista de Inscrições no Certame 
          display: [TbVaga,TbCidadeProva]
          table_method:  getInscricaoCandidato
          actions: {} 
          batch_actions: {}
          object_actions:
              _edit: ~
              _show: ~
              boleto: 
                  label: Gerar Boleto
      filter:  
          class: false
      form:    
          display: [id_vaga,id_condicao_especial,id_cidade_prova,id_idioma,vaga_deficiente]
      edit:    ~
      new:     ~
      show: 
          title: "Comprovante de Inscrição"
          
