<?php

/**
 * BasesfGuardPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $module_id
 * @property string $description
 * @property sfGuardModule $Modules
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $sfGuardGroupPermission
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $sfGuardUserPermission
 * 
 * @method string              get()                       Returns the current record's "name" value
 * @method integer             get()                       Returns the current record's "module_id" value
 * @method string              get()                       Returns the current record's "description" value
 * @method sfGuardModule       get()                       Returns the current record's "Modules" value
 * @method Doctrine_Collection get()                       Returns the current record's "Groups" collection
 * @method Doctrine_Collection get()                       Returns the current record's "sfGuardGroupPermission" collection
 * @method Doctrine_Collection get()                       Returns the current record's "Users" collection
 * @method Doctrine_Collection get()                       Returns the current record's "sfGuardUserPermission" collection
 * @method sfGuardPermission   set()                       Sets the current record's "name" value
 * @method sfGuardPermission   set()                       Sets the current record's "module_id" value
 * @method sfGuardPermission   set()                       Sets the current record's "description" value
 * @method sfGuardPermission   set()                       Sets the current record's "Modules" value
 * @method sfGuardPermission   set()                       Sets the current record's "Groups" collection
 * @method sfGuardPermission   set()                       Sets the current record's "sfGuardGroupPermission" collection
 * @method sfGuardPermission   set()                       Sets the current record's "Users" collection
 * @method sfGuardPermission   set()                       Sets the current record's "sfGuardUserPermission" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_permission');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('module_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardModule as Modules', array(
             'local' => 'module_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardGroupPermission',
             'local' => 'permission_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardGroupPermission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'permission_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}