<?php

/**
 * BasesfGuardModule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $sfGuardPermission
 * 
 * @method string              get()                  Returns the current record's "name" value
 * @method Doctrine_Collection get()                  Returns the current record's "sfGuardPermission" collection
 * @method sfGuardModule       set()                  Sets the current record's "name" value
 * @method sfGuardModule       set()                  Sets the current record's "sfGuardPermission" collection
 * 
 * @package    uerr
 * @subpackage model
 * @author     Marcel Nagm
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardModule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_module');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardPermission', array(
             'local' => 'id',
             'foreign' => 'module_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}