generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbColaborador
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_colaborador
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
          title: Lista de Colaboradores
          display: [nome,cpf,celular] 
      filter:  
          display: [nome,cpf,celular]
      form:    ~
      edit:    
          title: Editando Colaborador
      new:     
          title: Novo Colaborador
