all:
  mailer:
    param:
      transport:
        class: Swift_SmtpTransport
        param:
          host:       smtp.gmail.com
          port:       465
          encryption: ssl
          username: recadastramento@uerr.edu.br
          password: recadastramento-uerr
