generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbLocal
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_local
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
          title: Lista de Locais
          display: [nome,sigla]
      filter:  
          display: [nome,sigla]
      form:    ~
      edit:    
          title: Editar Local
      new:     
          title: Novo Local
