generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbCandidato
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_candidato
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:            
        class: false  
      form:    ~
      edit:    ~
      new:     
          title: 'Cadastro de Candidato'
          actions:
              _save: 
                  label: Cadastrar
