generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbProvaVaga
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_prova_vaga
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
          title: Lista de Vagas da Prova
          display: [TbVaga]
          table_method:  getPorProva
          actions:
              _new: ~
              Provas: 
                  label: Retornar Provas
          object_actions:
               _edit: ~
               _delete: ~
               Vagas:
                   label: Vagas 
      filter:  
          class: false
      form:    ~
      edit:    ~
      new:     ~
