<?php

/**
 * PluginsfGuardModuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardModuleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardModuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardModule');
    }
}