generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbLocalProva
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_local_prova
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
          title: Lista de Locais de Prova - "%%TbCertame%%"
          display: [Tb_local,status]
          actions:
              _new: ~
              Certames:
                  label: Lista de Certames
          table_method:  getPorCertame
          object_actions:
              _edit: ~
              _delete: ~
              SalaProva: 
                  label: Salas de Prova
      filter:  
          display: [id_local]
      form:    ~
      edit:    
      new:     
          actions:
              _save: ~
              _list: ~
              Local: 
                  label: Adicinar Local
