generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbLocalProva
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_local_prova
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  
          display: [id_certame]
      form:    ~
      edit:    ~
      new:     ~
