generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbIdioma
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_idioma
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
          title: "Lista de Idiomas"
      filter:  ~
      form:    ~
      edit:    
          title: "Editando Idioma"
      new:     
          title: "Novo Idioma"
