generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbProva
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          tb_prova
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          TbCertame: {label: Certame}
          TbVaga: {label: Vaga}
          id_certame: {label: Certame}
          id_vaga: {label: Vaga}
      list:    
          display: [TbVaga,data_inicio,hora_inicio,duracao]
          table_method:  getPorCertame
      filter:  
          display: [id_vaga]
      form:    ~
      edit:    ~
      new:     ~
