generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbProva
    theme:                 adminWithShow
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          tb_prova
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          TbCertame: {label: Certame}         
          id_certame: {label: Certame}
          id_vaga: {label: Vaga}
      list:
          title: Lista de Provas do certame        
          display: [data_inicio,hora_inicio,duracao,TbVaga]
          table_method:  getPorCertame
          actions:
              _new: ~
              Certames: 
                  label: Lista de Certames                        
          object_actions:
               _edit: ~
               _delete: ~               
               Questoes:
                   label: Questões 
               Alocacao:
                   label: Alocar Candidatos em Sala
               Locais: 
                  label: Locais de Prova    
               Gabarito: 
                  label: Cartões de Prova
               Correcao: 
                  label: Corrigir Cartões de Prova
                   
      filter:  
          class: false
      form:    ~
      edit:    ~
      new:     ~
